name: Package-build

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "audio/**"
      - "package/**"
      - "lib/**"
  pull_request:
    branches: [master]
    paths:
      - "audio/**"
      - "package/**"
      - "lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2

      - name: Install system dependencies
        run: |
          pip install selenium
          pip install webdriver-manager

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate the package
        run: yarn build

      - name: Build
        run: yarn && yarn build
        working-directory: package/

      - name: Test
        run: python3 test/selenium_test.py
        working-directory: package/
