name: Package-build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "audio/**"
      - "src/**"
      - "lib/**"
      - '.github/workflows/package.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - "audio/**"
      - "src/**"
      - "lib/**"
      - '.github/workflows/package.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Pre-build dependencies
        run: npm install yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate the package
        run: yarn build

      - name: Build
        run: yarn && yarn build

      - name: Test
        run: yarn test
