name: Web

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'package/**'
  pull_request:
    branches: [ master, v2.0 ]
    paths:
      - 'package/**'

defaults:
  run:
    working-directory: package

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]
        node-version: [lts/*]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}


    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build
